name: presence_microservice
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  debug:
    path: ../packages/debug
  mqtt:
    path: ../packages/mqtt
  HostBase:
    path: ../packages/HostBase
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
