name: MyQ
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  myq:
    path: ../pkg/myq
  debug:
    path: ../pkg/debug
  env:
    path: ../pkg/env
  mqtt:
    path: ../pkg/mqtt
  hostbase:
    path: ../pkg/hostbase
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
